# Generated by Django 4.2.5 on 2024-04-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMVP', '0002_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones'),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='categoria',
            field=models.CharField(choices=[('Turista', 'Turista'), ('Premiun', 'Premium')], max_length=20),
        ),
    ]
