# Generated by Django 4.2.5 on 2024-04-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMVP', '0004_remove_habitaciones_capacidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones'),
        ),
    ]
