# Generated by Django 4.2.5 on 2024-04-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMVP', '0005_habitaciones_imagen_1_habitaciones_imagen_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado')], default='Pendiente', max_length=20),
        ),
    ]
