ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER pacificreef IDENTIFIED BY pacificreef
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER pacificreef QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO pacificreef;
GRANT "CONNECT" TO pacificreef;
ALTER USER pacificreef DEFAULT ROLE "RESOURCE","CONNECT";