# Generated by Django 3.2.22 on 2024-04-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('descripción', models.TextField()),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(choices=[('Turista', 'Turista'), ('Premiun', 'Premiun')], max_length=20)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible')], max_length=20)),
            ],
        ),
    ]
